### PR TITLE
allow newer versions of lottie-web

### PR DESCRIPTION
**Pull request by ottob**
lots of improvements in recent versions:
https://github.com/airbnb/lottie-web/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by paambaati** [comment]
Lottie-Web `5.6.x` is out too, might as well upgrade to that!

**Comment by ottob** [comment]
`^5.5.9` will include `5.6.x` too since its a minor version upgrade. I verified this on https://semver.npmjs.com

**Comment by paambaati** [comment]
@ottob Oh of course, I think it is better to be more explicit if we're pushing out a new release now, when 5.6.x is out. It will signal to users that it has been tested on and supports the latest release.

**Comment by lazysergey** [comment]
v0.0.11 was updated to latest ^5.7.3

**Pull request closed without merging**
